<a href="https://colab.research.google.com/github/JeyTee1988/LLM-Schulung/blob/main/llm_schulung.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Wichtig**: Wenn Du dieses Notebook in Google Colab ausführst, wähle zuerst unter "Laufzeit > Laufzeittyp ändern" eine GPU aus, um die Ausführung zu beschleunigen.

# Transformer nutzen

Zunächst installieren wir die benötigte Library Huggingface Transformer

In [ ]:
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 17.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 22.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 45.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 50.2 MB/s eta 0:00:00


## Klassifizierung von Text

Wir laden eine Pipeline mit einem vortrainierten Sentiment-Modell. Das Modell kann explizit angegeben werden, ansonsten wird ein Standard-Modell (`distilbert-base-uncased-finetuned-sst-2-english`) genommen.

In [ ]:
from transformers import pipeline
classifier = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


Wir können das Modell nutzen, um die Stimmung eines Textes zu bestimmen. Hierbei wird angegeben, ob der Text positiv oder negativ ist und wie sicher das Modell ist bei der Bewertung.

In [ ]:
classifier(["We are happy to have you participate in our modest LLM workshop!", "Sorry that we had to cap the participant limit to 20"])

[{'label': 'POSITIVE', 'score': 0.9998558759689331},
 {'label': 'NEGATIVE', 'score': 0.9991243481636047}]

Dieses Modell wurde nur mit englischen Texten und scheinbar nicht mit Emoji trainiert:

In [ ]:
classifier(["Was ein schöner Tag für eine Schulung", "🤗", "😠"])

[{'label': 'NEGATIVE', 'score': 0.9137821793556213},
 {'label': 'NEGATIVE', 'score': 0.6970565319061279},
 {'label': 'NEGATIVE', 'score': 0.6970565319061279}]

## Textgenerierung

Wir laden das vortrainierte distilgpt2 Modell und nutzen es für Textgenerierung

In [ ]:
from transformers import pipeline

pipe = pipeline("text-generation", model="distilgpt2")

Wir können das Modell nutzen, um Texte zu vervollständigen.

In [ ]:
from transformers import set_seed
set_seed(42)
pipe("Hello, I’m a language model", max_length=20, num_return_sequences=5)



Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'Hello, I’m a language model but what I do in that role is to make everything'},
 {'generated_text': 'Hello, I’m a language model.” You’ll know the real name'},
 {'generated_text': 'Hello, I’m a language model’s\xadself, and I’m'},
 {'generated_text': 'Hello, I’m a language model, and I really wanted to make a nice API,'},
 {'generated_text': 'Hello, I’m a language model. I’think in any language. I�'}]

## Aufgabe: Nutzt Transformer auf andere Weise!

Spielt ein wenig mit der Pipeline rum:
- Probiert andere Texte aus
- Vergleicht verschiedene Modelle
- Nutzt einen anderen Anwendungsfall

Auf folgender Seite findet ihr weitere mögliche Anwendungsfälle
https://huggingface.co/docs/transformers/main/en/quicktour#pipeline

Probiert gerne was aus 🤗

# Transformer verstehen

Nun schauen wir in die Pipeline rein, um zu verstehen, wie Transformer funktionieren.

Die Pipeline stellt unser gesamtes Language Model dar. Sie besteht bei Transformern aus einem Tokenizer und dem eigentlichen Neuronalen Netz.

In [1]:
!pip install transformers einops accelerate

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 37.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 4.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 251.2/251.2 kB 24.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 31.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 85.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 71.8 MB/s eta 0:00:00


In [2]:
from transformers import pipeline

pipe = pipeline("text-generation", model="distilgpt2")

tokenizer = pipe.tokenizer
model = pipe.model

## Tokenizer

Der Tokenizer in einem (Large) Language Model (LLM) dient dazu, Text in kleinere Einheiten, sogenannte Tokens, zu zerlegen. Diese Tokens können einzelne Wörter, Phrasen oder sogar einzelne Buchstaben sein.

Der Tokenizer ist wichtig, weil ein LLM wie ein neuronales Netzwerk arbeitet, das auf Zahlen, nicht auf Wörtern, basiert. Es kann nicht direkt Text verstehen oder interpretieren. Stattdessen muss es den Text in eine numerische Form umwandeln, die es verarbeiten kann.

Dieser Prozess des Zerlegens und Umwandeln wird durch den Tokenizer durchgeführt. Er nimmt den ursprünglichen Text, teilt ihn in Tokens und wandelt diese dann in Zahlen um, die das Modell verarbeiten kann.

https://platform.openai.com/tokenizer


In [6]:
text = "We are happy to have you participate in our modest LLM workshop!"
tokenizer.tokenize(text)

['We',
 'Ġare',
 'Ġhappy',
 'Ġto',
 'Ġhave',
 'Ġyou',
 'Ġparticipate',
 'Ġin',
 'Ġour',
 'Ġmodest',
 'ĠLL',
 'M',
 'Ġworkshop',
 '!']

In [7]:
encoded_input = tokenizer(text, return_tensors='pt')
encoded_input.input_ids

tensor([[ 1135,   389,  3772,   284,   423,   345,  8277,   287,   674, 12949,
         27140,    44, 20243,     0]])

Der Tokenizer enthält ein Dictionary, welches jedem Token eine Zahl zuweist

In [8]:
vocab = tokenizer.get_vocab()
first_20_items = {k: vocab[k] for k in list(vocab.keys())[:20]}
first_20_items

{'Ġswell': 36214,
 'ocene': 34973,
 'Ġbuff': 6940,
 'ĠNetflix': 12074,
 'Ġstakeholders': 26138,
 'Friends': 36705,
 'Ġcortex': 20223,
 'ĠRuns': 44743,
 'Ġexperiments': 10256,
 'Ġguarant': 5505,
 'Ġprojected': 13301,
 'Ġbothered': 20466,
 'ĠApplications': 26622,
 'Neill': 26538,
 'Ġclearly': 4084,
 'Ġreflections': 35066,
 'Ġblowing': 19280,
 'olls': 33421,
 'ylene': 37880,
 'ĠPoly': 12280}

Es gibt insgesamt 50257 Tokens in diesem Tokenizer.

In [9]:
len(vocab)

50257

## Transformer-Modell

Das Modell ist der eigentliche Transformer, der den encodierten Text entgegen nimmt und verarbeitet oder *transformiert* 😎.

### Die Ausgabe verstehen

Statt die Pipeline als ganzes zu nutzen, können wir auch manuell die Ausgabe des Encoders durch unser Modell schleusen, um zu sehen, was es damit macht.

Obwohl wir nur den fehlenden Text vervollständigen wollen, liefert unser Transformer tatsächlich für **jedes** Token in unserem Input-Text eine Vorhersage für das nächste Token:

In [10]:
output = model(**encoded_input)
token_logits = output.logits

# Get the predicted token ids
predicted_token_ids = token_logits.argmax(dim=-1)
predicted_token_ids

tensor([[  383,   407,   284,  5453,   262,   319,   287,   262,  7865, 18066,
         15996,  1628,    13,   198]])

In [11]:
# Decode the tokens to text
predicted_text = [tokenizer.decode(t) for t in predicted_token_ids]

for index, t in enumerate(predicted_token_ids[0]):
  input_token = tokenizer.tokenize(text)[index]
  predicted_next_token = tokenizer.decode(t)
  print(input_token + " => " + predicted_next_token)


We =>  The
Ġare =>  not
Ġhappy =>  to
Ġto =>  announce
Ġhave =>  the
Ġyou =>  on
Ġparticipate =>  in
Ġin =>  the
Ġour =>  upcoming
Ġmodest =>  fundraising
ĠLL => VM
M =>  project
Ġworkshop => .
! => 



Das liegt daran, dass Transformer auf massiv parallele Verarbeitung und paralleles Training ausgelegt sind. Deswegen verarbeiten sie immer den gesamten Text parallel.

Um eine größere Spanne von Texten erzeugen zu können, nutzen Transformer nicht immer die wahrscheinlichste Vorhersage (Stichwort **Temperatur**).

Hier sind die fünf wahrscheinlichsten Vorhersagen:

In [16]:
import torch

# Convert logits to probabilities
token_probs = torch.nn.functional.softmax(token_logits, dim=-1)

# Get the top 5 predicted token ids
top_k = 5
top_k_probs, top_k_indices = token_probs.topk(top_k, dim=-1)

# Iterate over the tokens and print the top 5 predictions for each one
for i in range(top_k_indices.shape[1]):
    input_token = tokenizer.tokenize(text)[i]
    print(f"Input: {input_token}:")
    for j in range(top_k):
        token_id = top_k_indices[0, i, j].item()
        probability = top_k_probs[0, i, j].item()
        output_token = tokenizer.decode([token_id])
        print(f"    Output: '{output_token}', probability: {probability:.2%}")


Input: We:
    Output: ' The', probability: 4.03%
    Output: ' A', probability: 1.25%
    Output: 'The', probability: 1.19%
    Output: '
', probability: 1.12%
    Output: 'I', probability: 1.12%
Input: Ġare:
    Output: ' not', probability: 6.18%
    Output: ' going', probability: 2.36%
    Output: ' very', probability: 2.28%
    Output: ' all', probability: 2.03%
    Output: ' looking', probability: 1.96%
Input: Ġhappy:
    Output: ' to', probability: 75.27%
    Output: ' that', probability: 9.01%
    Output: ' with', probability: 5.26%
    Output: ' and', probability: 1.83%
    Output: ' we', probability: 1.26%
Input: Ġto:
    Output: ' announce', probability: 55.91%
    Output: ' be', probability: 4.09%
    Output: ' have', probability: 3.21%
    Output: ' share', probability: 3.20%
    Output: ' welcome', probability: 2.78%
Input: Ġhave:
    Output: ' the', probability: 10.51%
    Output: ' been', probability: 6.17%
    Output: ' a', probability: 5.33%
    Output: ' you', probabi

### Die Architektur verstehen


In [17]:
import torch
from transformers import GPT2Tokenizer, GPT2Model

# Laden des vortrainierten Modells und des zugehörigen Tokenizers
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2Model.from_pretrained('gpt2', output_hidden_states=True)

# GPU nutzen wenn verfügar
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = model.to(device).eval()

text = 'Das ist ein Beispieltext für die Demonstration.'

tokens = tokenizer.tokenize(text)
input_ids = tokenizer.convert_tokens_to_ids(tokens)

# Verfolgen der Veränderungen in den latenten Zuständen und Bestätigen der konstanten Dimension.
# Dazu führen wir die Eingabe durch das gesamte Modell und drucken die Größe der Ausgabe nach jedem Block
input_tensor = torch.tensor([input_ids], dtype=torch.long).unsqueeze(0).to(device)

with torch.no_grad():
    # Durchführen einer Vorwärtsdurchlaufe durch das Modell
    outputs = model(input_tensor)
    # Die Ausgabe ist ein Tuple, das die Endausgabe und eine Liste der Zwischenausgaben enthält
    final_output, hidden_states = outputs.last_hidden_state, outputs.hidden_states
    # Drucken Sie die Größe der Endausgabe und jeder Zwischenausgabe
    print(f"Größe der Endausgabe:\n\t{final_output.size()}\n")
    print(f"Endausgabe:\n\t{final_output}\n")
    for i, hidden_state in enumerate(hidden_states):
        print(f"Größe der latenten Zustände nach Block {i+1}:\n\t{hidden_state.size()}\n")
        print(f"Latente Zustände nach Block {i+1}:\n\t{hidden_state}\n\n")

Größe der Endausgabe:
	torch.Size([1, 1, 16, 768])

Endausgabe:
	tensor([[[[-0.1805, -0.1602, -0.2445,  ..., -0.1593,  0.0039, -0.0136],
          [-0.3021, -0.3064, -0.4753,  ...,  0.0716, -0.1752,  0.2778],
          [-0.6312, -0.3724, -0.7612,  ...,  0.3610, -0.1038,  0.0860],
          ...,
          [ 0.6071, -0.1206, -0.9526,  ..., -0.4354,  0.0310, -0.5339],
          [ 0.0030, -0.4362, -0.2058,  ..., -0.1486, -0.3879, -0.3260],
          [ 0.0698, -0.4597, -0.5089,  ..., -0.2768, -0.2152, -0.0472]]]],
       device='cuda:0')

Größe der latenten Zustände nach Block 1:
	torch.Size([1, 16, 768])

Latente Zustände nach Block 1:
	tensor([[[ 0.0911, -0.1488,  0.1890,  ..., -0.0553,  0.1373, -0.0367],
         [-0.0502, -0.2643, -0.0026,  ...,  0.1705, -0.0574, -0.0334],
         [-0.0055, -0.0747,  0.1101,  ...,  0.1342, -0.0187, -0.0468],
         ...,
         [-0.0501,  0.0583,  0.4026,  ..., -0.0276, -0.2199, -0.0523],
         [-0.0544,  0.0188,  0.1011,  ..., -0.0354, -0.1995, 